# Generated by Django 2.1.1 on 2018-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='licitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=60)),
                ('inicio', models.DateField()),
                ('tipo', models.CharField(choices=[('a', 'Licitacion'), ('b', 'Acuerdo marco')], max_length=1)),
                ('detalle', models.CharField(max_length=100)),
                ('fecha_ubicacion', models.DateField()),
                ('fecha_chekeo', models.DateField()),
                ('observaciones', models.CharField(max_length=1000)),
                ('importe', models.IntegerField()),
                ('importe_mensual', models.IntegerField()),
                ('pac', models.IntegerField()),
                ('inciso', models.CharField(choices=[('a', '2'), ('b', '3'), ('c', '4')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='auto',
        ),
    ]
