# Generated by Django 2.1.1 on 2018-08-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_licitaciones_proveedor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitaciones',
            name='fecha_chekeo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='licitaciones',
            name='fecha_ubicacion',
            field=models.DateField(null=True),
        ),
    ]
